class ErrorCode:
    AUXILIARY_MISMATCH = "AUXILIARY_MISMATCH"
    SUBJECT_VERB_MISMATCH = "SUBJECT_VERB_MISMATCH"
    CONNECTOR_MISMATCH = "CONNECTOR_MISMATCH"
    TEMPORAL_ADVERB_MISMATCH = "TEMPORAL_ADVERB_MISMATCH"
    TENSE_MISMATCH = "TENSE_MISMATCH"