services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: req_DB
      MYSQL_USER: root
      MYSQL_PASSWORD: rqadmin
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    # Importante: agregar healthcheck para que web espere
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  cliches-api:
    build:
      context: ../servicio-deteccion-cliches
      dockerfile: Dockerfile
    ports:
      - "8001:8001"

  repeticion-api:
    build:
      context: ../servicio-repeticion-palabras
      dockerfile: Dockerfile
    ports:
      - "8002:8002"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      cliches-api:
        condition: service_started
      repeticion-api:
        condition: service_started
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=req_DB
      - MYSQL_USER=rqadmin
      - MYSQL_PASSWORD=rqadminpassword
      - MYSQL_PORT=3306
      - API_CLICHES_URL=http://localhost:8001
      - API_WORD_REPETITION_URL=http://localhost:8002
volumes:
  dbdata:

