TEMP_VERB_RULES = {
    ("will","have","been","VBG"):"cont_perf_fut-fut",
    ("will","have","VBN"):"perf_fut-fut",
    ("will","be","VBG"):"cont_fut-fut",
    ("will","VB"):"simp_fut-fut",
    ("has","been","VBG"):"cont_perf_pres-pres",
    ("have","been","VBG"):"cont_perf_pres-pres",
    ("have","VBN"):"perf_pres-pres",
    ("has","VBN"):"perf_pres-pres",
    ("had","been","VBG"):"cont_perf_past-past",
    ("had","VBN"):"perf_past-past",
    ("was","VBG"):"cont_past-past",
    ("were","VBG"):"cont_past-past",
    ("am", "VBG"):"cont_pres-pres",
    ("are" , "VBG"):"cont_pres-pres",
    ("is", "VBG"):"cont_pres-pres",
    ("VBP",):"simp_pres-pres",
    ("VBZ",):"simp_pres-pres",
    ("VBD",):"simp_past-past",
}