import sys
from detector import is_passive, passive_positions, to_active_voice

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

def run_tests():
    print("=" * 65)
    print(" EJECUTANDO TESTS UNITARIOS: DETECTOR Y CONVERSOR DE VOZ PASIVA")
    print("=" * 65)

    # Test 1: Voz pasiva con agente
    s1 = "The letter was written by Juan."
    assert is_passive(s1) is True
    active1 = to_active_voice(s1)
    assert active1 == "Juan wrote the letter.", f"Esperado 'Juan wrote the letter.', obtenido '{active1}'"
    print(f"[TEST 1] Pasiva con agente:\n  Original : {s1}\n  Activa   : {active1} -> OK\n")

    # Test 2: Voz pasiva sin agente expreso
    s2 = "A bridge was built over the river."
    assert is_passive(s2) is True
    active2 = to_active_voice(s2)
    assert "built" in active2 and "bridge" in active2
    print(f"[TEST 2] Pasiva sin agente expreso:\n  Original : {s2}\n  Activa   : {active2} -> OK\n")

    # Test 3: Oración activa simple
    s3 = "Maria eats an apple."
    assert is_passive(s3) is False
    assert to_active_voice(s3) == s3
    print(f"[TEST 3] Oración activa (no pasiva):\n  Original : {s3}\n  Resultado: {to_active_voice(s3)} -> OK\n")

    # Test 4: Otra oración activa
    s4 = "John plays football."
    assert is_passive(s4) is False
    assert to_active_voice(s4) == s4
    print(f"[TEST 4] Oración activa (no pasiva):\n  Original : {s4}\n  Resultado: {to_active_voice(s4)} -> OK\n")

    # Test 5: Posiciones detectadas
    s5 = "The cake was eaten by Tom."
    positions = passive_positions(s5)
    assert isinstance(positions, list) and len(positions) > 0
    active5 = to_active_voice(s5)
    print(f"[TEST 5] Detección de rangos de caracteres:\n  Original   : {s5}\n  Posiciones : {positions}\n  Activa     : {active5} -> OK\n")

    # Test 6: Oración con modificador temporal y sintagma nominal complejo
    s6 = "The security report was generated by the automated server yesterday."
    assert is_passive(s6) is True
    active6 = to_active_voice(s6)
    assert "automated server generated" in active6.lower()
    assert "security report" in active6.lower()
    print(f"[TEST 6] Agente y sujeto complejos con modificador temporal:\n  Original : {s6}\n  Activa   : {active6} -> OK\n")

    # Test 7: Oración con frase introductoria previa al sujeto
    s7 = "At the end of the day, the system was created by the developer very quickly."
    assert is_passive(s7) is True
    active7 = to_active_voice(s7)
    assert "the developer created the system" in active7.lower()
    print(f"[TEST 7] Frase introductoria y circunstancial posterior:\n  Original : {s7}\n  Activa   : {active7} -> OK\n")

    # Test 8: Párrafo multioración (pasiva + activa)
    s8 = "The security report was generated by the automated server yesterday. The system runs smoothly."
    active8 = to_active_voice(s8)
    assert "the system runs smoothly" in active8.lower()
    print(f"[TEST 8] Párrafo multioración:\n  Original : {s8}\n  Activa   : {active8} -> OK\n")

    print("=" * 65)
    print(" [OK] TODOS LOS TESTS PASARON EXITOSAMENTE (8/8)")
    print("=" * 65)

if __name__ == "__main__":
    run_tests()
